dataset: "KiDS"

settings_parameters:
  image_size: 64
  precision: "float32"
  size_dataset: 1.0
  

logging_parameters:
  out_dir: "output_galaxiesKiDS"
  log_interval: 30
  eval_iters: 10
  init_from: "scratch"
  num_epochs: 100

model_parameters:
  in_channels: 3
  latent_dimension: 128
  kld_weight: 0.00025
  hidden_dimensions: [32, 64, 128, 256, 512]

training_parameters:
  batch_size: 1024
  kld_weight: 0.00025
  max_lr: 0.005
  gamma: 0.95
  weight_decay: 0.0
  decay_lr: True
  grad_clip: 1.0





